package ai.pipi.dotapickone

import android.util.Log

class Hero {
    companion object {
        private var herolist = listOf (
            "Abaddon",
            "Alchemist",
            "Ancient_Apparition",
            "Anti_Mage",
            "Arc_Warden",
            "Axe",
            "Bane",
            "Batrider",
            "Beastmaster",
            "Bloodseeker",
            "Bounty_Hunter",
            "Brewmaster",
            "Bristleback",
            "Broodmother",
            "Centaur_Warrunner",
            "Chaos_Knight",
            "Chen",
            "Clinkz",
            "Clockwerk",
            "Crystal_Maiden",
            "Dark_Seer",
            "Dark_Willow",
            "Dawnbreaker",
            "Dazzle",
            "Death_Prophet",
            "Disruptor",
            "Doom",
            "Dragon_Knight",
            "Drow_Ranger",
            "Earthshaker",
            "Earth_Spirit",
            "Elder_Titan",
            "Ember_Spirit",
            "Enchantress",
            "Enigma",
            "Faceless_Void",
            "Grimstroke",
            "Gyrocopter",
            "Hoodwink",
            "Huskar",
            "Invoker",
            "Io",
            "Jakiro",
            "Juggernaut",
            "Keeper_of_the_Light",
            "Kez",
            "Kunkka",
            "Legion_Commander",
            "Leshrac",
            "Lich",
            "Lifestealer",
            "Lina",
            "Lion",
            "Lone_Druid",
            "Luna",
            "Lycan",
            "Magnus",
            "Marci",
            "Mars",
            "Medusa",
            "Meepo",
            "Mirana",
            "Monkey_King",
            "Morphling",
            "Muerta",
            "Naga_Siren",
            "Nature_s_Prophet",
            "Necrophos",
            "Night_Stalker",
            "Nyx_Assassin",
            "Ogre_Magi",
            "Omniknight",
            "Oracle",
            "Outworld_Devourer",
            "Pangolier",
            "Phantom_Assassin",
            "Phantom_Lancer",
            "Phoenix",
            "Primalbeast",
            "Puck",
            "Pudge",
            "Pugna",
            "Queen_of_Pain",
            "Razor",
            "Riki",
            "Ringmaster",
            "Rubick",
            "Sand_King",
            "Shadow_Demon",
            "Shadow_Fiend",
            "Shadow_Shaman",
            "Silencer",
            "Skywrath_Mage",
            "Slardar",
            "Slark",
            "Snapfire",
            "Sniper",
            "Spectre",
            "Spiritbreaker",
            "Storm_Spirit",
            "Sven",
            "Techies",
            "Templar_Assassin",
            "Terrorblade",
            "Tidehunter",
            "Timbersaw",
            "Tinker",
            "Tiny",
            "Treant_Protector",
            "Troll_Warlord",
            "Tusk",
            "Underlord",
            "Undying",
            "Ursa",
            "Vengeful_Spirit",
            "Venomancer",
            "Viper",
            "Visage",
            "Voidspirit",
            "Warlock",
            "Weaver",
            "Windranger",
            "Winter_Wyvern",
            "Witch_Doctor",
            "Wraith_King",
            "Zeus"
        )

        private val heroPosition: Map<Int, List<Int>> = mapOf(
            1 to listOf(1),
            2 to listOf(3,4),
            3 to listOf(4,5),
            4 to listOf(1),
            5 to listOf(4,5),
            6 to listOf(1,2),
            7 to listOf(2,3,4),
            8 to listOf(1),
            9 to listOf(2,4),
            10 to listOf(1),
            11 to listOf(1,2),
            12 to listOf(1),
            13 to listOf(2),
            14 to listOf(1,2,3,4,5),
            15 to listOf(1,2,3),
            16 to listOf(2,3),
            17 to listOf(2),
            18 to listOf(1),
            19 to listOf(1,2,3,4),
            20 to listOf(1,2,3,4,5),
            21 to listOf(1,2,3,4,5),
            22 to listOf(2,4,5),
            23 to listOf(2,3),
            25 to listOf(1,2,4),
            26 to listOf(2,4,5),
            27 to listOf(4,5),
            28 to listOf(2,3),
            29 to listOf(3),
            30 to listOf(4,5),
            31 to listOf(4,5),
            32 to listOf(1,2,4),
            33 to listOf(3,4),
            34 to listOf(2,4),
            35 to listOf(1,2,4),
            36 to listOf(1,2,3),
            37 to listOf(4,5),
            38 to listOf(2,3),
            39 to listOf(1,2,3,4),
            40 to listOf(1,2,3,4,5),
            41 to listOf(1),
            42 to listOf(1,3),
            43 to listOf(2,3),
            44 to listOf(1),
            45 to listOf(2,4,5),
            46 to listOf(1,2),
            47 to listOf(1,2,3),
            48 to listOf(1),
            49 to listOf(1,2,3),
            50 to listOf(2,4,5),
            51 to listOf(4,5),
            52 to listOf(2,4),
            53 to listOf(1,2,3,4,5),
            54 to listOf(1),
            55 to listOf(3),
            56 to listOf(1,2),
            57 to listOf(3),
            58 to listOf(4),
            59 to listOf(2),
            60 to listOf(1,3),
            61 to listOf(1,2),
            62 to listOf(4),
            63 to listOf(1,3,4),
            64 to listOf(2,4,5),
            65 to listOf(2,4),
            66 to listOf(),
            67 to listOf(1),
            68 to listOf(4,5),
            69 to listOf(1,3),
            70 to listOf(1),
            71 to listOf(3,4),
            72 to listOf(1,4),
            73 to listOf(1,4),
            74 to listOf(2,4),
            75 to listOf(2,4,5),
            76 to listOf(2),
            77 to listOf(1,2,3),
            78 to listOf(3),
            79 to listOf(4,5),
            80 to listOf(1,2),
            81 to listOf(1,3),
            82 to listOf(2),
            83 to listOf(4,5),
            84 to listOf(2,3,4,5),
            85 to listOf(3,4,5),
            86 to listOf(2,4,5),
            87 to listOf(4,5),
            88 to listOf(2,4),
            89 to listOf(1),
            90 to listOf(2,4),
            91 to listOf(4,5),
            92 to listOf(2,3),
            93 to listOf(1),
            94 to listOf(1,2),
            95 to listOf(1),
            96 to listOf(3),
            97 to listOf(1,2,3,4,5),
            98 to listOf(2,3),
            99 to listOf(1,3),
            100 to listOf(4,5),
            101 to listOf(2,4,5),
            102 to listOf(1,3,4,5),
            103 to listOf(4),
            104 to listOf(1,2,3),
            105 to listOf(2,4,5),
            106 to listOf(1,2),
            107 to listOf(2,4),
            108 to listOf(3),
            109 to listOf(1),
            110 to listOf(2,3,4),
            111 to listOf(5),
            112 to listOf(3,4,5),
            113 to listOf(1,2),
            114 to listOf(1,2,4),
            119 to listOf(4,5),
            120 to listOf(2,3),
            121 to listOf(4,5),
            123 to listOf(4),
            126 to listOf(2,3),
            128 to listOf(2,4,5),
            129 to listOf(2,3),
            131 to listOf(4,5),
            135 to listOf(2,3,4),
            136 to listOf(1,2,3,4,5),
            137 to listOf(2,3),
            138 to listOf(1,4),
            145 to listOf(1,2),
        )
    }

    fun fetchPosition(stratzId:Int):List<Int>{
        if(heroPosition[stratzId] != null){
            return heroPosition[stratzId]!!
        }
        else
            Log.d(javaClass.simpleName,"no such stratzId: " + stratzId.toString())
        return emptyList()
    }

    fun fetchData(): List<String> {
        return herolist
    }
    fun getpicname(index:Int): String{
        return herolist[index] + "_icon.png"
    }
    fun getlength(): Int{
        return herolist.size
    }
}